//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMagicCube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public int Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int State2 { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public string UpdateUserName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateUserName { get; set; }
    
        public virtual School School { get; set; }
    }
}
