//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMagicCube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IDNumber { get; set; }
        public string MobilePhone { get; set; }
        public string SchoolName { get; set; }
        public string ClassName { get; set; }
        public int GuardianType1 { get; set; }
        public string GuardianName1 { get; set; }
        public string GuardianMobilePhone1 { get; set; }
        public int GuardianType2 { get; set; }
        public string GuardianName2 { get; set; }
        public string GuardianMobilePhone2 { get; set; }
        public string GuardianOccupation2 { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public int State { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public string UpdateUserName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public string GuardianOccupation1 { get; set; }
    
        public virtual School School { get; set; }
    }
}
